import Foundation
import Network

let root = URL(fileURLWithPath: "/Users/grit/.agent-dashboard")
let rootPath = root.standardizedFileURL.path
let topicsPath = "/Users/grit/.agent-memory/topics"
let boardFile = root.appendingPathComponent("board.json")
let dataJsFile = root.appendingPathComponent("data.js")
let port: UInt16 = 8787

let mimeTypes = [
    "html": "text/html; charset=utf-8",
    "js": "text/javascript; charset=utf-8",
    "json": "application/json",
    "css": "text/css; charset=utf-8",
    "png": "image/png",
    "svg": "image/svg+xml",
    "ico": "image/x-icon",
]

func respond(_ conn: NWConnection, status: String, contentType: String, body: Data) {
    let header = "HTTP/1.1 \(status)\r\nContent-Type: \(contentType)\r\nContent-Length: \(body.count)\r\n"
        + "Access-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: GET, POST, OPTIONS\r\n"
        + "Access-Control-Allow-Headers: Content-Type\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n"
    var out = Data(header.utf8)
    out.append(body)
    conn.send(content: out, completion: .contentProcessed { _ in conn.cancel() })
}

func jsonReply(_ conn: NWConnection, status: String, object: [String: Any]) {
    let body = (try? JSONSerialization.data(withJSONObject: object, options: [.prettyPrinted])) ?? Data("{}".utf8)
    respond(conn, status: status, contentType: "application/json", body: body)
}

// MARK: - File engine

func regenerateDataJs() -> [String: Any] {
    var groups: [String: [[String: Any]]] = [:]
    guard let enumerator = FileManager.default.enumerator(atPath: topicsPath) else { return [:] }
    for case let rel as String in enumerator {
        guard rel.hasSuffix(".md") else { continue }
        let topic = rel.split(separator: "/").first.map(String.init) ?? "misc"
        let full = topicsPath + "/" + rel
        guard let attrs = try? FileManager.default.attributesOfItem(atPath: full),
              let data = FileManager.default.contents(atPath: full),
              let text = String(data: data, encoding: .utf8) else { continue }
        var title = (rel as NSString).lastPathComponent
        for line in text.split(separator: "\n", omittingEmptySubsequences: false).prefix(5) {
            if line.hasPrefix("# ") { title = line.dropFirst(2).trimmingCharacters(in: .whitespaces); break }
        }
        let mtime = (attrs[.modificationDate] as? Date) ?? Date()
        let iso = ISO8601DateFormatter().string(from: mtime)
        groups[topic, default: []].append([
            "name": (rel as NSString).lastPathComponent,
            "path": ".agent-memory/topics/" + rel,
            "topic": topic,
            "title": title,
            "mtime": iso,
            "bytes": data.count,
        ])
    }
    let library = groups.keys.sorted().map { ["topic": $0, "files": groups[$0]!] }
    let board = (try? JSONSerialization.jsonObject(with: Data(contentsOf: boardFile))) as? [String: Any] ?? [:]
    let payload: [String: Any] = [
        "generatedAt": ISO8601DateFormatter().string(from: Date()),
        "board": board,
        "library": library,
    ]
    if let json = try? JSONSerialization.data(withJSONObject: payload, options: [.prettyPrinted]) {
        var out = Data("// auto-generated by dashboard-server (Swift) - DO NOT EDIT\nwindow.DASHBOARD_DATA = ".utf8)
        out.append(json)
        out.append(Data(";\n".utf8))
        try? out.write(to: dataJsFile)
    }
    return ["topics": library.count, "files": groups.values.reduce(0) { $0 + $1.count }]
}

func moveCard(cardId: String, column: String) -> Bool {
    guard var board = (try? JSONSerialization.jsonObject(with: Data(contentsOf: boardFile))) as? [String: Any],
          var cards = board["cards"] as? [[String: Any]],
          let columns = board["columns"] as? [[String: Any]] else { return false }
    guard columns.contains(where: { $0["id"] as? String == column }),
          let idx = cards.firstIndex(where: { $0["id"] as? String == cardId }) else { return false }
    let now = ISO8601DateFormatter().string(from: Date())
    cards[idx]["column"] = column
    cards[idx]["updated"] = now
    board["cards"] = cards
    board["updated"] = now
    guard let out = try? JSONSerialization.data(withJSONObject: board, options: [.prettyPrinted]) else { return false }
    try? out.write(to: boardFile)
    return true
}

// MARK: - HTTP handling

func handleRequest(_ conn: NWConnection, raw: Data) {
    guard let text = String(data: raw.prefix(16384), encoding: .utf8) else {
        respond(conn, status: "400 Bad Request", contentType: "text/plain", body: Data("bad request\n".utf8))
        return
    }
    let headEnd = text.range(of: "\r\n\r\n")
    let head = headEnd.map { String(text[..<$0.lowerBound]) } ?? text
    let bodyData = headEnd.map { Data(String(text[$0.upperBound...]).utf8) } ?? Data()
    let lines = head.split(separator: "\r\n").map(String.init)
    let first = lines.first?.split(separator: " ").map(String.init) ?? []
    let method = first.count > 0 ? first[0] : ""
    let rawPath = first.count > 1 ? first[1] : "/"

    if method == "OPTIONS" {
        respond(conn, status: "204 No Content", contentType: "text/plain", body: Data())
        return
    }

    var path = rawPath.split(separator: "?", maxSplits: 1).first.map(String.init) ?? "/"
    path = (path.removingPercentEncoding ?? path).trimmingCharacters(in: CharacterSet(charactersIn: "/"))

    switch (method, path) {
    case ("GET", "api/health"):
        jsonReply(conn, status: "200 OK", object: ["ok": true, "ts": ISO8601DateFormatter().string(from: Date())])
    case ("POST", "api/refresh"):
        let stats = regenerateDataJs()
        jsonReply(conn, status: "200 OK", object: ["ok": true].merging(stats) { _, new in new })
    case ("POST", "api/kanban-move"):
        print("MOVE raw=\(raw.count) body=\(bodyData.count) str=[\(String(data: bodyData, encoding: .utf8) ?? "nil")]")
        fflush(stdout)
        guard let obj = try? JSONSerialization.jsonObject(with: bodyData) as? [String: Any],
              let cardId = obj["cardId"] as? String, let column = obj["column"] as? String else {
            print("MOVE parse-fail"); fflush(stdout)
            jsonReply(conn, status: "400 Bad Request", object: ["ok": false, "error": "invalid move"])
            return
        }
        guard moveCard(cardId: cardId, column: column) else {
            print("MOVE precondition-fail id=\(cardId) col=\(column)"); fflush(stdout)
            jsonReply(conn, status: "400 Bad Request", object: ["ok": false, "error": "invalid move"])
            return
        }
        let stats = regenerateDataJs()
        jsonReply(conn, status: "200 OK", object: ["ok": true, "moved": cardId, "column": column].merging(stats) { _, new in new })
    case ("GET", let p) where p.hasPrefix("mem/"):
        let rel = String(p.dropFirst(4))
        let memRoot = URL(fileURLWithPath: topicsPath).standardizedFileURL
        let resolved = memRoot.appendingPathComponent(rel).standardizedFileURL
        guard resolved.path.hasPrefix(memRoot.path) else {
            respond(conn, status: "403 Forbidden", contentType: "text/plain", body: Data("forbidden\n".utf8))
            return
        }
        guard resolved.pathExtension.lowercased() == "md",
              FileManager.default.fileExists(atPath: resolved.path), !resolved.hasDirectoryPath else {
            respond(conn, status: "404 Not Found", contentType: "text/plain", body: Data("not found\n".utf8))
            return
        }
        if let body = try? Data(contentsOf: resolved) {
            respond(conn, status: "200 OK", contentType: "text/markdown; charset=utf-8", body: body)
        } else {
            respond(conn, status: "500 Internal Server Error", contentType: "text/plain", body: Data("read error\n".utf8))
        }
    case ("GET", let p):
        let file = p.isEmpty ? "index.html" : p
        let resolved = root.appendingPathComponent(file).standardizedFileURL
        guard resolved.path.hasPrefix(rootPath) else {
            respond(conn, status: "403 Forbidden", contentType: "text/plain", body: Data("forbidden\n".utf8))
            return
        }
        guard FileManager.default.fileExists(atPath: resolved.path), !resolved.hasDirectoryPath else {
            respond(conn, status: "404 Not Found", contentType: "text/plain", body: Data("not found\n".utf8))
            return
        }
        let mime = mimeTypes[resolved.pathExtension.lowercased()] ?? "application/octet-stream"
        if let body = try? Data(contentsOf: resolved) {
            respond(conn, status: "200 OK", contentType: mime, body: body)
        } else {
            respond(conn, status: "500 Internal Server Error", contentType: "text/plain", body: Data("read error\n".utf8))
        }
    default:
        respond(conn, status: "405 Method Not Allowed", contentType: "text/plain", body: Data("method not allowed\n".utf8))
    }
}

func readRequest(_ conn: NWConnection, _ buf: Data) {
    conn.receive(minimumIncompleteLength: 1, maximumLength: 65536) { data, _, isComplete, error in
        var b = buf
        if let d = data, error == nil { b.append(d) }
        guard error == nil else { conn.cancel(); return }
        if let sep = b.range(of: Data("\r\n\r\n".utf8)) {
            let head = String(data: b.subdata(in: b.startIndex..<sep.lowerBound), encoding: .utf8) ?? ""
            let cl = head.split(separator: "\r\n")
                .first { $0.lowercased().hasPrefix("content-length:") }
                .flatMap { Int($0.split(separator: ":", maxSplits: 1)[1].trimmingCharacters(in: .whitespaces)) } ?? 0
            let bodyStart = b.distance(from: b.startIndex, to: sep.upperBound)
            if b.count >= bodyStart + cl {
                handleRequest(conn, raw: b)
                return
            }
        }
        if isComplete {
            handleRequest(conn, raw: b)
            return
        }
        readRequest(conn, b)
    }
}

func handle(_ conn: NWConnection) {
    conn.start(queue: DispatchQueue.global())
    readRequest(conn, Data())
}

let listener = try NWListener(using: .tcp, on: NWEndpoint.Port(rawValue: port)!)
listener.stateUpdateHandler = { state in
    switch state {
    case .ready:
        print("dashboard-server (swift) listening on http://127.0.0.1:\(port)")
        fflush(stdout)
    case .failed(let err):
        print("listener failed: \(err)")
        fflush(stdout)
        exit(1)
    default:
        break
    }
}
listener.newConnectionHandler = { conn in
    conn.start(queue: DispatchQueue.global())
    handle(conn)
}
listener.start(queue: DispatchQueue.global())
dispatchMain()
